### ISSUE TITLE
.NET Coreはプロジェクト管理ではなく開発フレームワークに分類するのが適切

### ISSUE THREAD

**Issue by yamadakou** [ossforumjp/oss-choukanzu#2]
「.NET Core」が「開発支援」内の「プロジェクト管理」に分類されていますが、「.NET Core」のリンク先のページに以下の記述がありますので、「開発フレームワーク」に分類するのが適切と考えます。
```
.NET は、最新のアプリと強力なクラウド サービスを構築するための無料のオープンソースのクロスプラットフォーム フレームワークです。
```

■「.NET Core」のリンク先
https://dotnet.microsoft.com/ja-jp/

**Comment by t-yoneshi** [comment]
お返事遅れましたが、ご指摘ありがとうございました。次回更新時に分類を変更します。
