### ISSUE TITLE
FreeRTOSが並列するOSと比べて異色

### ISSUE THREAD

**Issue by soburi** [ossforumjp/oss-choukanzu#3]
FreeRTOSはOSには違いないが、同一の項目はすべてLinux, UNIX等で、
組み込み用途がメインのFreeRTOSを同じカテゴリに入れるのは、
間違ってはいないが違和感がある。
OSSのRTOSでは ZephyrRTOS(https://www.zephyrproject.org/), NuttX(https://nuttx.apache.org/), TOPPERS(https://www.toppers.jp/)があり、
IoTと関連付けて整理すると比較的収まりが良いかと思う。

**Comment by t-yoneshi** [comment]
コメントありがとうございます。カテゴリの新設を検討するようにします。
