### ISSUE TITLE
TeraTerm の URL

### ISSUE THREAD

**Issue by nmaya** [ossforumjp/oss-choukanzu#4]
鳥瞰図では TeraTerm が https://github.com/TeraTermProject/osdn-download へリンクしています。
このリポジトリは OSDN の不調に対応したときの一時的なものです。

現在は、プロジェクトのWebサイトは https://teratermproject.github.io/ 、リポジトリは https://github.com/TeraTermProject/teraterm となっています。

cf. アナウンス
https://twitter.com/Tera_Term/status/1722999393001808068
https://twitter.com/Tera_Term/status/1725492015746670785

**Comment by t-yoneshi** [comment]
ありがとうございます。
Webサイトである、https://teratermproject.github.io/ 
 こちらに変更するようにします。
