### ISSUE TITLE
PuTTY の URL

### ISSUE THREAD

**Issue by nmaya** [ossforumjp/oss-choukanzu#5]
鳥瞰図では PuTTY が https://www.putty.org/ へリンクしています。
PuTTY の URL は https://www.chiark.greenend.org.uk/~sgtatham/putty/ ではないでしょうか。

putty.org ドメインは [Bitvise SSH Server/Client](https://en.wikipedia.org/wiki/Bitvise) の開発元 [Bitvise](https://www.bitvise.com/about-us) が取得しているようです。

> How did Bitvise acquire this domain?
> Bitvise was not the original registrant of putty.org. We purchased it from a previous owner who used it in ways unrelated to software. We thought it useful to repurpose it the way you see.

**Comment by t-yoneshi** [comment]
こちらもありがとうございます。
ご指摘のとおり、https://www.chiark.greenend.org.uk/~sgtatham/putty/
こちらのURLへ変更します。ご指摘感謝します。
